---
- name: Install unattended-upgrades
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  tags: unattended_upgrades

- name: Configure automatic reboot
  ansible.builtin.template:
    src: 50unattended-upgrades-reboot.jinja
    dest: /etc/apt/apt.conf.d/50unattended-upgrades-reboot
    owner: root
    group: root
    mode: "0644"
  tags: unattended_upgrades
