---
wg_easy_version: "15.1"
wg_easy_admin_username: "admin"
wg_easy_host: "{{ ansible_default_ipv4.address }}"
wg_easy_port: "51820"
wg_easy_dns: "1.1.1.1,1.0.0.1"
wg_easy_ipv4_cidr: "10.10.0.0/24"
wg_easy_ipv6_cidr: "fd10:10:10::/64"
wg_easy_allowed_ips_extra: ""
wg_easy_bridge_ip: "10.42.42.42"
wg_easy_bridge_subnet: "10.42.42.0/24"
wg_easy_bridge_host_ip: "10.42.42.1"
