---
# Docker bridge network for WireGuard container
wg_easy_bridge_ip: "10.43.43.43"
wg_easy_bridge_subnet: "10.43.43.0/24"
wg_easy_bridge_host_ip: "10.43.43.1"

# AdGuard DNS IPs (unfiltered)
adguard_dns_ipv4_primary: "94.140.14.14"
adguard_dns_ipv4_secondary: "94.140.15.15"
adguard_dns_ipv6_primary: "2a10:50c0::ad1:ff"
adguard_dns_ipv6_secondary: "2a10:50c0::ad2:ff"

# Compose DNS server list for WireGuard
wg_easy_dns: "{{ adguard_dns_ipv4_primary }},{{ adguard_dns_ipv4_secondary }},{{ adguard_dns_ipv6_primary }},{{ adguard_dns_ipv6_secondary }}"

# Android Private DNS needs to reach DNS servers before VPN is established
# These IPs must be in allowed IPs so clients can reach them
wg_easy_allowed_ips_extra: "{{ adguard_dns_ipv4_primary }}/32,{{ adguard_dns_ipv4_secondary }}/32,{{ adguard_dns_ipv6_primary }}/128,{{ adguard_dns_ipv6_secondary }}/128"
