---
- name: Configure SSH hardening
  ansible.builtin.template:
    src: ssh-hardening.conf.jinja
    dest: /etc/ssh/sshd_config.d/ssh-hardening.conf
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags: ssh_hardening

- name: Ensure SSH service is running and enabled
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
  tags: ssh_hardening
