---
- name: Setup server
  hosts: all
  become: true
  roles:
    - server_essentials
    - nodejs
    - geerlingguy.docker
    - wg_easy
    - ssh_hardening
    - ufw
    - fail2ban
    - unattended_upgrades

